name: USCriminalRecordsAgency
favicon: null
layout_spectrum: 0.20896176458336413
typography_spectrum: 0.5728453223127872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.18599188746884465
  lightness: 0.5461263954639435
  saturation: 0.45162559929303825
  rhythmicContrast: 0.7575213827658445
purpose: []
